### ISSUE TITLE
Overhaul Review Manager Guidelines

### ISSUE THREAD

**Issue by gkampmeier** [tdwg/process#2]
Per the request of the TDWG Exec, a ticket is being initiated about the revision of the May 15, 2009 "Guidelines for Review Managers for Proposed TDWG Standards" by Lee Belbin. The interest in this update was sparked by an email 3 Feb 2021 from Steve Baskauf, in his concern ([expressed for GGBN](https://github.com/tdwg/ggbn/issues/3)) in the transparency of the review process. 

He polled known former review managers of TDWG Standards to find the document (no longer found on the website, broken link [http://www.tdwg.org/fileadmin/documentation/guidance_docs/ReviewManagerGuidelines.doc](http://www.tdwg.org/fileadmin/documentation/guidance_docs/ReviewManagerGuidelines.doc) ), which both Dag Endresen and Gail Kampmeier retained backup copies. It was then converted to a [Google Doc](https://docs.google.com/document/d/1sgVmbB9HKKLb74IhH-JYPUbZOZkJ_yqf/edit) for collaborative editing. 

Further, the TDWG Exec asked, in their 9 Feb 2021 Zoom meeting, that a target date for the revision be ready for review. It is tentatively suggested that this be 1 March 2021.

**Comment by baskaufs** [comment]
I support the March 1 deadline. Since this is a revision, it should not take us longer than that unless there are policy questions. I am also now subscribed to this repo, so I will get notifications of future comments here.

**Comment by baskaufs** [comment]
The following issues are blocking completion of this task:

- [x] [Should expert reviews be kept private or made public?](https://github.com/tdwg/process/issues/3) / [Section 5.2, line 197](https://github.com/tdwg/process/blob/master/review_manager.md#52-example-of-an-email-to-potential-reviewers) Also address the issue of whether anonymity is required or desirable, see [item 1 in Section 1.3, line 54](https://github.com/tdwg/process/blob/master/review_manager.md#13-independent-reviewers)
- [x] [Must comments in public review be made public?](https://github.com/tdwg/process/issues/4) / [Section 3.3, line 117](https://github.com/tdwg/process/blob/master/review_manager.md#33-post-review), [Section 4, line 144 and following lines](https://github.com/tdwg/process/blob/master/review_manager.md#4-public-review)
- [x] [Form of tracking system for correspondence related to review process and expert reviews](https://github.com/tdwg/process/issues/5) / [Section 2, line 61](https://github.com/tdwg/process/blob/master/review_manager.md#2-tdwg-standards-track), [Section 3.1  line 89](https://github.com/tdwg/process/blob/master/review_manager.md#31-reviewer-profile), [Section 5.2 line 209](https://github.com/tdwg/process/blob/master/review_manager.md#52-example-of-an-email-to-potential-reviewers)
- [x] [What are mechanisms to alert the community of the status of public review?](https://github.com/tdwg/process/issues/6) / [Section 4, line 131](https://github.com/tdwg/process/blob/master/review_manager.md#4-public-review)
- [x] [Revise recommendation about file formats used during the review process](https://github.com/tdwg/process/issues/9) / [Section 2, line 67](https://github.com/tdwg/process/blob/master/review_manager.md#2-tdwg-standards-track)
- [x] [How shall we recommend the submission be made visible to the public?](https://github.com/tdwg/process/issues/10) / [Section 4, line 129](https://github.com/tdwg/process/blob/master/review_manager.md#4-public-review)
- [x] [Assemble examples of communications related to past public reviews](https://github.com/tdwg/process/issues/7) / [Section 5.3, entire section](https://github.com/tdwg/process/blob/master/review_manager.md#53-example-of-public-review-announcement)

**Comment by baskaufs** [comment]
@gkampmeier @Tasilee @dagendresen I had originally planned to try to migrate the shared doc to Markdown by now in an attempt to keep up with the 1 March timeframe. However, I haven't had time yet. But I hope to get to it this weekend so we can wrap this up.

**Comment by stanblum** [comment]
Hey Steve,

I have a GoogleDoc plugin that helps with the conversion to markdown.  Want
me to go ahead with that, or would you like to begin by creating the next
version in GoogleDocs?

-Stan

**Comment by baskaufs** [comment]
Well, if you want to start with that, it would be fine. 

I was going to try to go through the document to see if there were points of agreement and just incorporate that into the Markdown version, but really anyone could do that and we can work from that. In the end, I'm assuming this can go on the website somewhere, so we'd want Markdown for that. I was also going to try to put some of the standard document formatting that would indicate version date, that it is not part of a standard, citation, etc. But that can be added to the Markdown as we go along.

**Comment by stanblum** [comment]
My feeling is that it's easier to write and edit in Google Doc than in
Markdown.  I would be inclined to do the writing and editing there, and
only when we think we have a near final version that we make the switch to
Markdown.

**Comment by baskaufs** [comment]
I agree that Google docs are easier for editing. Perhaps I was deluded into thinking we were closer to done than we are. One thing that I wanted to do was to link the issues blocking the completion of the task to particular lines in the document, which can't be done in the Google doc as easily as in the Markdown. But perhaps the edit/rewrite should be done in a Google doc first. Whatever you think will move this forward is fine with me.

**Comment by baskaufs** [comment]
@gkampmeier @dagendresen @Tasilee  I have converted the Google Doc into Markdown. I formatted it to be consistent with other TDWG documents (header section, section numbering system, etc.) as well as adding the header necessary for it to play well with the TDWG website. Based on the Google doc, I made all of what I considered to be cosmetic edits (deleting obsolete text, etc.)

The document has a number of italicized comments that eventually need to be replaced with new text that replaces the removed obsolete text. I have linked each instance of needed text with the corresponding issue in the tracker. As we replace each italicized blob we can close the corresponding issue. I realize that working in Markdown may not be as convenient as working in a Google doc, but at this point we have a fixed number of edits that we need to make and I feel like our remaining discussion needs to be permanently archived in a way not possible with Google Docs. I use Atom, which has a Markdown preview to do the editing, so it is easy for me to do the actual editing of the document if I have appropriate replacement text. It looks like this:

![image](https://user-images.githubusercontent.com/5765781/111306500-45088e80-8626-11eb-8a6e-7e2cb96c7d8c.png)

So if you three can help write the text blobs, I'm happy to manage the actual editing of the Markdown if you aren't comfortable with doing the editing yourself. I have actually created a branch called `revisions_round1`, which we should use for the edits rather than editing the `master` branch. That will allow us to view diffs between the original document and the revised document as we go along. There is a [pull request](https://github.com/tdwg/process/pull/11) open to help with tracking our linear progress as we push new commits. 

So here is how I propose we move forward. There are seven issues blocking completion of the revision (linked in the checkboxes above). If you want to take on one or more of these issues, go to the issue and assign it to yourself. Create a blob of text that you think is a good solution to the issue and either push it to the `revisions_round1` branch yourself or paste it into a comment block in the relevant issue and I'll add it to the doc myself. We can then discuss whether we agree that this solves the issue. In some cases, we may need to ask the Exec or other parties for practical or policy advice. 

We have already missed the preliminary deadline for completion, but I feel like there has been enough discussion already that most of the issues can be resolved if someone just writes something. So I would propose that we establish a new goal of completion by April 1.

**Comment by dagendresen** [comment]
I have added links from the [revisions_round1/review_manager.md](https://github.com/tdwg/process/blob/revisions_round1/review_manager.md) to the respective issues.

**Comment by baskaufs** [comment]
Alright, this has dragged on much longer than I originally anticipated (typical for a TDWG project), but I've thrashed my way through [a draft](https://github.com/tdwg/process/blob/revisions_round1/review_manager.md) that at least attempts to address all of the issues we discussed. I've left Issue #6 open for the time being until everyone has had a chance to examine the diff showing the edits made related to that issue.

To compare all of the edits made to the starting version (the master branch) view [this page](https://github.com/tdwg/process/compare/master...revisions_round1). You will need to click on the "files changed" tab, then scroll to the bottom of the page and click on "Load diff".

@gkampmeier @Tasilee @dagendresen, it would be great if you could give the entire document a read-through to see how it flows, whether any text is misplaced, and any other editorial changes that would clean it up. Also, I've probably thoroughly polluted it with American English spellings, so feel free so suggest changes to make spellings internally consistent.  When we all feel the draft is satisfactory, I'll merge [the pull request](https://github.com/tdwg/process/pull/11) so that the branch we've been working on (revisions_round1) gets incorporated into the master branch. At that point, we can ask the Executive to review it.

**Comment by baskaufs** [comment]
Oh, one more think I thought of. I think in other documents, contributor affiliations have been listed. If you want your affiliation listed after your name, let me know what to use (or just edit the branch with this yourself). I will probably use "Vanderbilt University Libraries" for myself.

**Comment by gkampmeier** [comment]
@baskaufs forgive my ignorance, but I am not yet used to working in GitHub at this level and do not know how best to either suggest or make small editorial changes (e.g., missing commas; that/which; spelling) as I find them in your diff docs (e.g., [https://github.com/tdwg/process/commit/0dcb2649113b78897d8dd2c537e0878e3057ec55](https://github.com/tdwg/process/commit/0dcb2649113b78897d8dd2c537e0878e3057ec55). I would appreciate help or a place where this is explained (understanding this process is very valuable to me as the power of GitHub becomes increasingly apparent). Thanks!

**Comment by baskaufs** [comment]
No problem @gkampmeier, we have all been in that place at one time! 

There are two approaches that you can take. 

The simplest is to just edit the Markdown online. To do this, you need to get the page for the relevant document, https://github.com/tdwg/process/blob/revisions_round1/review_manager.md , on your screen. From anywhere within the repository, drop down the branch selection at the upper left (starts off at "master" or "main" for newer repositories), and select the branch. The one we are working on is `revisions_round1`. 

Then click on the document to edit. In this case, it's `review_manager.md`. On the right near the top of the document is a little pencil icon. Click that and you'll get to an editing screen. You have to edit the raw Markdown, but in this document, we aren't using anything very complicated so hopefully the editing markup will be apparent to you. Here's a [cheatsheet](https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf) if anything doesn't make sense. For stuff like commas and regular text edits, just stick them in.

When you are done, enter a brief descriptive commit message in the box just below the "Commit changes" header (e.g. "proofreading edits"). I usually skip the optional extended description. For this kind of work, you can just keep the default radio button "Commit directly to the ... branch". If you were doing really major and questionable edits, you could create a new branch, but that would add unnecessary complexity here. Then click the "Commit changes" button. Your commit will show up in the history along with all of the other changes we've made.

The second alternative (the way I usually edit) is to clone the repository locally, make the changes on my local computer using a code editor, then push the changes to GitHub. This is probably unnecessary for you in this case unless you actually want to learn more about how to use GitHub more fully. If you do decide to go this route, I would recommend using the GitHub Desktop software rather than suffering through doing all of the Git commands using the command line. That is heresy to the hard-core Git users, but honestly, I almost never find any need for doing command-line Git. 

If you are interested in this second option, I would shamelessly recommend my [Beginner GitHub video lessons](https://heardlibrary.github.io/digital-scholarship/manage/control/github/). They are a series of very short follow-along videos based on GitHub Desktop and are focused on the fundamental ideas of basic GitHub use (commits, cloning, pushing and pulling, etc.).  I do not yet have videos about the more advanced topics such as branching and managing projects with GitHub, but there are some pages with screenshots and explanation linked at the bottom of the page I've referenced above.

Please feel free to ask if you have any other questions. I've learned what I know about GitHub by just jumping in and using it, and seeing how expert users like @peterdesmet manage projects. As you've seen in this project, there are a lot of capabilities to combine managing issues associated with incremental changes to a complex document.

**Comment by gkampmeier** [comment]
Thanks, @baskaufs --the piece I was missing was how to get back to something I could edit. I'm doing this, but in the course of it have run into an issue:

line 139 "However, comments may also be emailed to the Review Manager in two circumstances: if the commenter is unable to use the issue tracker or if the commenter wishes to remain anonymous. Although the default is signed comments, anonymous comments may be accepted at the Review Manager's discretion. _In either circumstance_, the Review Manager should post the comments to the tracker on behalf of the submitter."

Italics are mine.  Just before this, it is stated that the RM has discretion at accepting anonymous comments, but this phrase indicates the opposite. Not sure how to reword this. Perhaps "...the Review Manager should post _accepted_ comments to...

**Comment by gkampmeier** [comment]
@baskaufs @Tasilee @dagendresen it occurs to me that we do not define the "Author," yet we use it throughout. At one point I had added Author(s) and then realized we had probably defined this term as being one or more people submitting the proposed standard. I've now gone back to the top and see this isn't the case.  In looking at the Process document, this person is referred to as the Task Group Convener (Author is simpler for our use). Should this actually be 1.1 under responsibilities?

**Comment by gkampmeier** [comment]
@baskaufs if others give affiliations, mine is rather long "Illinois Natural History Survey, Prairie Research Institute, University of Illinois at Urbana-Champaign" --perhaps it is more appropriate to provide links to our ORCIDs? Mine is [https://orcid.org/0000-0002-5178-4170](https://orcid.org/0000-0002-5178-4170)

**Comment by baskaufs** [comment]
@gkampmeier With regards to line 139, what I intended was that the RM could post text from an email in either the case of a person who had trouble using the tracker or someone who had an anonymous comment. If you can clarify this, that would be awesome.

**Comment by baskaufs** [comment]
Good point about "Author", it needs to be defined. It was the term used in the previous version and I didn't change it. I would consider the "authors" to be the members of the task group, who presumably wrote the documents with the convener. However, in the case of a complicated standard like DwC, there were different authors for various documents included in the standard. Perhaps the simplest thing would be to change "Author" to "Authors", then define "Authors" at the top as members of the task group participating in drafting documents included in the standard. One could also just add that the RM communicates with the Authors through the Task Group convener.

**Comment by baskaufs** [comment]
I like the ORCID idea. I don't think it's been done before, but it's better than affiliations because they change over time. I would support just providing ORCIDs. Mine is https://orcid.org/0000-0003-4365-3135, @dagendresen is https://orcid.org/0000-0002-2352-5497, and @Tasilee is https://orcid.org/0000-0001-8900-6203 (already looked up for lots of people [here](https://github.com/tdwg/rs.tdwg.org/blob/master/docs/docs-authors.csv)).

**Comment by gkampmeier** [comment]
@baskaufs do I need to wait until you finish going through my edits before giving a go at line 139? Want to start with the latest ...

**Comment by baskaufs** [comment]
Sorry, I should have indicated that was the only issue I had with the edits you pushed. Go for it!

**Comment by dagendresen** [comment]
@gkampmeier no worries if you edit while @baskaufs is working on a local copy. When syncing a local git to the shared online git we will get a warning for any conflicts and the option to easily resolve these (to not write over what others have done).

**Comment by stanblum** [comment]
Steve,   This is another tremendous contribution to TDWG's social infrastructure (process!).  I have a couple of additions/modifications I'd like to make (review managers and conflicts of interest; situations when a review manager can make comments on issues in a review).  I might not get them posted until Wednesday.

**Comment by baskaufs** [comment]
@stanblum No problem, just jump in when you are ready.

**Comment by gkampmeier** [comment]
@baskaufs I think I may see one of my issues (confusion) with working with GitHub here.  I am using the default "Commit directly" to the revisions_round1 branch when I hit the Commit changes button.  Should I have changed this to Create a new branch...?

**Comment by dagendresen** [comment]
I believe Steve recommended that we all commit directly to the `revisions_round1` branch 

(a new branch is mostly useful when making comments to code that could break something, or for larger proposed changes that might be controversial and might not be implemented after all)

**Comment by debpaul** [comment]
@dagendresen small typo, see "joural" in review_manager.md

**Comment by dagendresen** [comment]
Thanks, I have merged to the "revisions_round1" branch
I have also added a [few other typo updates](https://github.com/tdwg/process/commits/revisions_round1/review_manager.md)

**Comment by baskaufs** [comment]
Lots of good typo corrections! Thanks for the detailed look.

**Comment by baskaufs** [comment]
I think we can say that the overhaul is mostly done, with the exception of possible additional comments by @stanblum . I don't see any reason not to just merge the branch we were editing now -- we can still make additional edits in the master branch. 

Given that the comments on this issue are long but mostly dealt with, I will open a new umbrella issue where we can discuss what still needs to be done to wrap this up.
